language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-license-.+

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew :skygear:test :skygear:connectedAndroidTest --info --stacktrace

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: SkygearIO/skygear-SDK-Android
    tags: true

env:
  global:
    - BINTRAY_USER="skygeario-builder"
    # BINTRAY_API_KEY
    - secure: "AA1JqW1GST/LEaaRCfdYmBPvMfoutSzSQlXOzTDOK/gccatphpW2vqf3KbA7ukDKpSwiIAVn4yttV/5MVQ8corvHXF5Vz5SqYfjM/g92JaKdP6DA4q5sAWzP86JhRqbuD12Vi9JvxlWbAWGcAF6CfMuXIeL09XdA0BQwm0D29+RyGkfv/Lit2aTBIcUWbhnOI3VF22lqwi9iwoJvMXkTzNcXQNSpViLjYhnsI/s0GFdqV45kLwY7ZeWzODG76sVJov9cIIegD8PKdO/wtO5HXBbDqsCC1GYSRQ7YmW1ec8VFBSghdb0IuQzh7mcCIauD0jTeRg4Kgz8Kj7sHvgrd4JUSv0kROSq+ANY0oX5W+S/WnvuT/IqluPCzfmDcv0Quyw4w2vSG/G8aVqXkX5eASbV9p4dMCnuM+PDdvQSKEA/jRCU0PatMRh30G3LdLn8NuNue8KBox36VTpZNYj0eIaoU8Sbab92iWnnEGS/LiAu1Th/dCSXHcKlRkOgI2GeggLnntOzqK/6VDhyrIyo9tWcNXRBNzWaqITPuER3Ryd2I218doPrOlDQAh+cOX1t7j8BPZTFeFRuEbLBcIQmN9IhjnczI6yBL7C0jLWu1RLOS9AQgcyV3CnpTBr5enBxCaLzJoUH4mDU4sEqdjtwnE996n87XI5HAF9DZNPhZSZw="

notifications:
  slack:
    secure: "verBlT6aN1p/5HNUfShAOL5iaySB0n+SF+2IDlDXrdnJ1WCA+DYYnW7HHZPGTwoZ4YaEkjyDhQwB/1flj6y3yOuk/xgGgWIQiCeO9pZWnhdtHl8fS3Kr/g49VGrem/Nq0Pqm6f2YO2K33vioGHi3BV8blfs8vJdnYmQMRqzse+RQ7D1tfUn6FEYGQdBp4Xt/J2H0nsptsYzU7KHf1efcTHl7zS2kfMkaXXQnLN+H29AMILxn7b5//FxIm+bC6NZIjSOqiCBc4livcDOjjf8NS4utpsTXc0IIwx/6CqJcfRGpA/dLQJmPT5pJ8tSUthU2zcWqlfki2lpTi/CMja7wD8j9qGWCBkkmjX3fNblMOuJ21c62p+ikahsDTnzZ83kH+bIGG1IN9o7kL0Ksc9tocfn+HDzodOVAZt09p2YCzkAedqfm9eSMCSoXQzd6zzdWNzMXdiz7XXSfcZ5cVq7FPYwV+RrGwt0vbWZPEmNv8pvx5+bXjwwE+bms/1i///TZUZ1VYnzJ0u/Il/WsHGyjD7buQfqyxYHvqGd1Io1SXOVNHJ/pR0W1XJepQiY9c1za8YUyVgxVwncrqUFYgHGXbPSQJO09aTortYVHTq+icjTVJWBhKy5mB29LoGoR5JkJTCTdjvzbNFpCQin7D9toRNF3j79vB1PszArk7fvuzWM="
